image: luki42/flutter-rust

stages:
  - build

flutter_build_android:
  stage: build
  script:
    - make translation
    - make apk
    - mv build/app/outputs/apk/release/app-release.apk ./wormhole.apk
  artifacts:
    paths:
      - wormhole.apk

flutter_lint:
  stage: build
  script:
    - flutter format . --output none --set-exit-if-changed

flutter_analyze:
  stage: build
  script:
    - flutter analyze ./lib
