name: wormhole
description: A magic-wormhole client UI
version: 1.0.0+3
publish_to: 'none'

environment:
  sdk: ">=3.7.2"
  flutter: '>= 3.29.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_gen_runner:

  # flutter rust interop
  ffi: ^2.1.4
  flutter_rust_bridge: 2.10.0
  freezed_annotation: ^3.0.0

  # file chooser / open / share
  file_picker: ^10.1.9
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  open_filex: ^4.6.0

  # qr scanner/generation
  barcode_widget: ^2.0.4

  provider: ^6.1.5 # easy wrapper for changenotifier
  shared_preferences: ^2.5.2 # store key/value pairs on disk
  share_handler: ^0.0.17 # receive share intents from other apps
  vibration: ^3.1.3 # trigger phone vibrations
  intl: any # handle translations
  # fluttertoast: ^8.2.1 # fancy toast popups
  toggle_switch: ^2.0.1
  permission_handler: ^12.0.0
  url_launcher: ^6.1.9

  # use custom plugin for handling programmatically close of app
  flutter_close_app:
    git:
      url: https://gitlab.com/lukas-heiligenbrunner/fluttercloseapp.git
      ref: master
  flutter_zxing: 2.0.0
  device_info_plus: ^11.4.0
  rust_lib_wormhole:
    path: rust_builder

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  ffigen: ^19.0.0
  flutter_launcher_icons:
  build_runner:
  freezed: ^3.0.4

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

flutter_intl:
  main_locale: zh_CN
  enabled: true

# app icon generation
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "bitmap.png"
  min_sdk_android: 29
