name: wormhole
description: A magic-wormhole client
version: 1.0.1
publish_to: 'none'

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # flutter rust interop
  ffi: 2.0.1
  flutter_rust_bridge: 1.62.0
  meta: 1.8.0
  freezed_annotation: ^2.2.0

  # file chooser / open / share
  file_picker: 5.2.5
  path_provider: 2.0.12
  share_plus: 6.3.0
  open_filex: 4.3.2

  # qr scanner/generation
  barcode_widget: 2.0.3
  mobile_scanner: 2.1.0

  provider: 6.0.5 # easy wrapper for changenotifier
  shared_preferences: 2.0.17 # store key/value pairs on disk
  receive_sharing_intent: 1.4.5 # receive share intents from other apps
  vibration: 1.7.6 # trigger phone vibrations
  intl: 0.17.0 # handle translations
  fluttertoast: 8.1.2 # fancy toast popups
  toggle_switch: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  ffigen: ^7.2.4
  flutter_launcher_icons:
  build_runner:
  freezed: ^2.3.2

# The following section is specific to Flutter packages.
flutter:
  # auto generate translations
  generate: true

  # include material icons
  uses-material-design: true

# app icon generation
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "bitmap.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
