name: wormhole
description: A magic-wormhole client
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # flutter rust interop
  ffi: ^2.1.3
  flutter_rust_bridge: ^2.9.0
  freezed_annotation: ^2.4.4

  # file chooser / open / share
  file_picker: ^9.0.3
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  open_filex: ^4.6.0

  # qr scanner/generation
  barcode_widget: ^2.0.4

  provider: ^6.1.1 # easy wrapper for changenotifier
  shared_preferences: ^2.0.18 # store key/value pairs on disk
  share_handler: ^0.0.17 # receive share intents from other apps
  vibration: ^1.7.7 # trigger phone vibrations
  intl: ^0.19.0 # handle translations
  # fluttertoast: ^8.2.1 # fancy toast popups
  toggle_switch: ^2.0.1
  permission_handler: ^11.1.0
  url_launcher: ^6.1.9

  # use custom plugin for handling programmatically close of app
  flutter_close_app:
    git:
      url: https://gitlab.com/lukas-heiligenbrunner/fluttercloseapp.git
      ref: master
  flutter_zxing: ^1.6.0
  device_info_plus: ^10.0.1
  rust_lib_wormhole:
    path: rust_builder
  
# dependency_overrides:
  # win32: ^5.5.4
  # archive: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  ffigen: ^14.0.0
  flutter_launcher_icons:
  build_runner:
  freezed: ^2.5.8

# The following section is specific to Flutter packages.
flutter:
  # auto generate translations
  generate: true

  # include material icons
  uses-material-design: true

# app icon generation
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "bitmap.png"
  min_sdk_android: 30 # android min sdk min:16, default 21
